global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bitcoin'
    static_configs:
      - targets: ['bitcoin-exporter:9332']

  - job_name: 'lightning'
    static_configs:
      - targets: ['lnd-exporter:9092']